name:                www
version:             0.1.0.0
github:              "tungd/www"
license:             Apache-2.0
author:              "Tung Dao"
maintainer:          "me@tungdao.com"
copyright:           "(c) 2018 Tung Dao"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tungd/www#readme>

dependencies:
- base >= 4.7 && < 5
- rio
- wai
- wai-extra
- web-routes
- aeson
- http-types
- blaze-html

default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- ScopedTypeVariables

ghc-options:
- -Wall

library:
  source-dirs: src

tests:
  www-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - www
